# Generated by Django 4.1.5 on 2023-02-07 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cities", "0002_alter_city_options_alter_city_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Train",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Номер потяга"
                    ),
                ),
                ("travel_time", models.IntegerField(verbose_name="Час в дорозі")),
                (
                    "from_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_city",
                        to="cities.city",
                        verbose_name="Звідки",
                    ),
                ),
                (
                    "to_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_city",
                        to="cities.city",
                        verbose_name="Куди",
                    ),
                ),
            ],
            options={
                "verbose_name": "Потяг",
                "verbose_name_plural": "Потяги",
                "ordering": ["name"],
            },
        ),
    ]
